### ISSUE TITLE
Is it possible to also route traffic to an API Gateway using this setup?

### ISSUE THREAD

**Issue by stvius** [aws-samples/aws-iot-endpoint-with-static-ips#1]
I have a requirement to whitelist one static ip for a device behind a firewall.
Using this architecture, the MQTT communications with IoT core using a static IP is solved.
My device is linux based, there are other required functionalities e.g. invoking and Api gateway for Just in time registration.
Is it possible to use the same static IP to communicate with an apigw using this architecture?
Thank you in advance.

**Comment by Kriechi** [comment]
@stvius this architecture only provides static IPs for the IoT Core endpoints via HTTP and MQTT.

You could adapt the general blueprint for API Gateway, using a VPC Link to bring the API into your VPC, and then put a Network Load Balancer with Elastic IPs in front of it.

Another option is to use Global Accelerator in front of your API, see https://aws.amazon.com/blogs/networking-and-content-delivery/accessing-an-aws-api-gateway-via-static-ip-addresses-provided-by-aws-global-accelerator/

Another option is to use a VPN-based solution, see the blog post (towards the end) for more details.
