### ISSUE TITLE
Error with custom endpoint :AWS_ERROR_MQTT_UNEXPECTED_HANGUP

### ISSUE THREAD

**Issue by baahujain** [aws-samples/aws-iot-endpoint-with-static-ips#3]
I am running into awscrt.exceptions.AwsCrtError when I try to connect using custom end point as below
```
python3 pubsub.py --endpoint  iot.my-domain.com --port 8883 --cert third_thing-certificate.pem.crt --key third_thing-private.pem.key --root-ca AmazonRootCA1.pem --client-id basicPubSub  --topic s
dk/test/Python --count 1       
```    

```
Connecting to iot.my-domain.com with client ID 'basicPubSub'...
Traceback (most recent call last):
  File "pubsub.py", line 133, in <module>
    connect_future.result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AWS_ERROR_MQTT_UNEXPECTED_HANGUP: The connection was closed unexpectedly.
```

But if I use the iot end-point eg:a3d6610xxxxty-ats.iot.ap-south-1.amazonaws.com , then I dont see this error.

**Comment by Kriechi** [comment]
Hi @baahujain,

I see in your command line arguments port 8883 and use-websockets.
Please try with a valid port+protocol combination, see https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

On port 8883, you should use MQTT directly, without MQTT.

Also, you can enable AWS IoT logging to CloudWatch - please check there for any connection-related log events.

**Comment by baahujain** [comment]
Hi @Kriechi ,I pasted a wrong command( I edited the post with correct command). Even with the correct command it was failing.
But I could figure out the issue !!
The newly added custom domain (can be seen in settings section of AWS Iot console) was in disabled state . everything worked find after I enabled it.
